#!/usr/bin/expect
spawn /usr/games/gnuchess --uci
send "position fen 4R2k/5ppp/3p4/pp2qr2/3pPPP1/P5P1/1P6/1K6 w KQkq - \r"
send "go depth 2 \r"
expect { board_init_list {puts illegal}
         bestmove {puts bestmove}}
send "quit \r"
